---
title: "Predictions Based on 2011-2023 Home Attendance Records"
format: pdf
editor: visual
messages: FALSE
warnings: FALSE
---

This document seeks to utilize attendance records of Duke University home football games from the previous 12 seasons (2011-2023) to predict the number of attendees at Duke football home games during the 2024 season.

# Packages

```{r}
#| label: load-packages

library(tidyverse)
library(tidymodels)

```

# Importing the Dataset

```{r}
#| label: load-data

att_data <- read_csv("data/Duke Stats - DukeAttendanceV3.csv")

att_data <- att_data |>
  mutate(Day = as.factor(Day))

home_att_data <- att_data |>
  filter(Site == "Home")

opp_list <- c("Elon", "Connecticut", "Florida St.",
              "North Carolina", "SMU", "Virginia Tech")

home_att_data

```

# Attendance History for 2024 Opponents

```{r}
#| label: 2024opp-past-attendance

home_att_data |>
  filter(OppName %in% opp_list) |>
  ggplot(
    aes(x = 0, y = AttPct)
  ) +
  geom_point(alpha = 0.333) +
  facet_wrap(~OppName, strip.position = "top", nrow = 1) +
  scale_x_continuous(labels = NULL, breaks = NULL) +
  labs(x = "Opponent",
       y = "Attendance (% of stadium capacity filled)")

home_att_data |>
  filter(OppName %in% opp_list) |>
  ggplot(
    aes(x = 0, y = AttNum)
  ) +
  geom_point(alpha = 0.4) +
  facet_wrap(~OppName, strip.position = "top", nrow = 1) +
  scale_x_continuous(labels = NULL, breaks = NULL) +
  labs(x = "Opponent",
       y = "Attendance (# of people)")

```

## Elon

```{r}
#| label: elon-past-attendance

home_att_data |>
  filter(OppName == "Elon") |>
  ggplot(
    aes(x = Year, y = AttPct)
  ) +
  geom_point() +
  labs(x = "Year",
       y = "Attendance (% of stadium capacity filled)")
```

## Connecticut

## Florida St.

## North Carolina

```{r}
#| label: unc-past-attendance

home_att_data |>
  filter(OppName == "North Carolina") |>
  ggplot(
    aes(x = Year, y = AttPct)
  ) +
  geom_point() +
  labs(x = "Year",
       y = "Attendance (% of stadium capacity filled)")
```

## SMU

## Virginia Tech
